# Generated by Django 4.1.7 on 2023-03-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_like_comment_is_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_to_comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
    ]
