# Generated by Django 4.1.7 on 2023-03-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_authuser_last_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
    ]
