# Generated by Django 4.1.7 on 2023-03-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_rename_followers_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='avatar_url',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='authuser',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
