# Generated by Django 4.1.7 on 2023-03-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_post',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
